/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reservasimeja;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
/**
 *
 * @author ASUS
 */
public class DetailReservasi extends javax.swing.JFrame {
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    DatabaseConnection d = new DatabaseConnection();
    
    /**
     * Creates new form DetailReservasi
     */
    public DetailReservasi() {
        initComponents();
        d.connect();
        refreshTabel();
        refreshCombo();
    }
    
    
    class transaksi extends DetailReservasi{
        int id_transaksi,id_menu,no_meja,jumlah_orang,harga,jumlah_beli,total_bayar;
        String nama_pelanggan,tanggal,waktu,nama_menu;

        public transaksi() {
            try {
                Date date = txt_tanggal.getDate();
                DateFormat dateformat = new SimpleDateFormat("YYYY-MM-dd");
                this.tanggal = dateformat.format(date);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
            this.waktu = txt_waktu.getText();
            this.jumlah_orang = Integer.parseInt(txt_jumlahorang.getText());
            String selectedMeja = comb_nomeja.getSelectedItem().toString();
            this.no_meja = Integer.parseInt(selectedMeja.split(" ")[1]);
            String combo = comb_idmenu.getSelectedItem().toString();
            String[] arr =combo.split(":");
            this.nama_pelanggan = txt_namapelanggan.getText();
            this.id_menu = Integer.parseInt(arr[0]);
            nama_menu = arr[1];
            harga = Integer.parseInt(arr[2]);
            this.jumlah_beli = Integer.parseInt(txt_jumlahbeli.getText());
            this.total_bayar = this.harga * this.jumlah_beli;
               
        }
    }
    
    public void refreshTabel(){
        model = new DefaultTableModel();
        model.addColumn("ID Transaksi");
        model.addColumn("Nama Pelanggan");
        model.addColumn("ID Menu");
        model.addColumn("Tanggal");
        model.addColumn("Waktu");
        model.addColumn("No Meja");
        model.addColumn("Jumlah Orang");
        model.addColumn("Nama Menu");
        model.addColumn("Harga");
        model.addColumn("Jumlah Beli");
        model.addColumn("Total Bayar");
        table_transaksi.setModel(model);
        try {
            this.stat = d.getCon().prepareStatement("select*from transaksi");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {                
                Object[] data = {
                  rs.getString(1),
                  rs.getString(2),
                  rs.getString(3),
                  rs.getString(4), 
                  rs.getString(5), 
                  rs.getString(6), 
                  rs.getString(7), 
                  rs.getString(8),
                  rs.getString(9), 
                  rs.getString(10), 
                  rs.getString(11)                     
                };
                model.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        txt_waktu.setText("");
        txt_jumlahorang.setText("");
        txt_idtransaksi.setText("");
        txt_namapelanggan.setText("");
        txt_jumlahbeli.setText("");
        txt_totalbayar.setText("");        
    }
    
    public void refreshCombo(){
        try {
            this.stat = d.getCon().prepareStatement("select*from menu where status = 'Tersedia'");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {                
                comb_idmenu.addItem(rs.getString("id_menu")+":"+
                rs.getString("nama_menu")+":"+
                rs.getString("harga"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comb_nomeja = new javax.swing.JComboBox<>();
        btn_invoice = new javax.swing.JButton();
        txt_jumlahorang = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_input = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        txt_waktu = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btn_layout = new javax.swing.JButton();
        txt_jumlahbeli = new javax.swing.JTextField();
        txt_idtransaksi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_namapelanggan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        comb_idmenu = new javax.swing.JComboBox<>();
        txt_totalbayar = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_transaksi = new javax.swing.JTable();
        btn_logout = new javax.swing.JButton();
        txt_tanggal = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("TRANSAKSI");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Tanggal");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("No Meja");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Jumlah Orang");

        comb_nomeja.setBackground(new java.awt.Color(255, 255, 204));
        comb_nomeja.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        comb_nomeja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meja 1 (2-4 Orang)", "Meja 2 (1-2 Orang)", "Meja 3 (8-12 Orang)", "Meja 4 (4-8 Orang)" }));

        btn_invoice.setBackground(new java.awt.Color(204, 204, 204));
        btn_invoice.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_invoice.setText("CETAK INVOICE");
        btn_invoice.setAlignmentY(1.0F);
        btn_invoice.setBorderPainted(false);
        btn_invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_invoiceActionPerformed(evt);
            }
        });

        txt_jumlahorang.setBackground(new java.awt.Color(255, 255, 204));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setText("Reservasi Meja");

        btn_input.setBackground(new java.awt.Color(0, 153, 0));
        btn_input.setForeground(new java.awt.Color(255, 255, 255));
        btn_input.setText("Input");
        btn_input.setAlignmentY(1.0F);
        btn_input.setBorderPainted(false);
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(0, 123, 255));
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Update");
        btn_update.setAlignmentY(1.0F);
        btn_update.setBorderPainted(false);
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 0, 0));
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Delete");
        btn_delete.setAlignmentY(1.0F);
        btn_delete.setBorderPainted(false);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        txt_waktu.setBackground(new java.awt.Color(255, 255, 204));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setText("Waktu");

        btn_layout.setBackground(new java.awt.Color(204, 204, 204));
        btn_layout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_layout.setText("Layout Meja");
        btn_layout.setAlignmentY(1.0F);
        btn_layout.setBorderPainted(false);
        btn_layout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_layoutActionPerformed(evt);
            }
        });

        txt_jumlahbeli.setBackground(new java.awt.Color(255, 255, 204));

        txt_idtransaksi.setBackground(new java.awt.Color(255, 255, 204));
        txt_idtransaksi.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Id Transaksi");

        txt_namapelanggan.setBackground(new java.awt.Color(255, 255, 204));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setText("Nama pelanggan");

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setText("Pre-Order Menu");

        btn_menu.setBackground(new java.awt.Color(204, 204, 204));
        btn_menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_menu.setText("Daftar Menu");
        btn_menu.setAlignmentY(1.0F);
        btn_menu.setBorderPainted(false);
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setText("ID Menu");

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel19.setText("Jumlah Beli");

        comb_idmenu.setBackground(new java.awt.Color(255, 255, 204));
        comb_idmenu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        txt_totalbayar.setBackground(new java.awt.Color(255, 255, 204));
        txt_totalbayar.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel20.setText("Total Bayar");

        table_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Transaksi", "Nama Pelanggan", "Daftar Menu", "Tanggal", "Waktu", "No Meja", "Jumlah Orang", "Jumlah Beli", "Total Bayar"
            }
        ));
        table_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_transaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_transaksi);

        btn_logout.setBackground(new java.awt.Color(204, 204, 204));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.setAlignmentY(1.0F);
        btn_logout.setBorderPainted(false);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        txt_tanggal.setBackground(new java.awt.Color(255, 255, 204));
        txt_tanggal.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_invoice)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(comb_idmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_menu))
                        .addComponent(jLabel20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(284, 284, 284)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_logout))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txt_idtransaksi)
                                            .addGap(79, 79, 79))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(comb_nomeja, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btn_layout))
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel18)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(80, 80, 80)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_totalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(79, 79, 79)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_input, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel15)
                                    .addComponent(txt_jumlahorang)
                                    .addComponent(txt_waktu)
                                    .addComponent(jLabel16)
                                    .addComponent(txt_namapelanggan)
                                    .addComponent(txt_jumlahbeli))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_waktu, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txt_tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_jumlahorang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb_nomeja, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_layout, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idtransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_namapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_jumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb_idmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_totalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_input, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        try {
            transaksi t = new transaksi();
            txt_totalbayar.setText(""+t.total_bayar);
            this.stat = d.getCon().prepareStatement("insert into transaksi values (?,?,?,?,?,?,?,?,?,?,?)");
            this.stat.setInt(1,0);
            this.stat.setString(2,t.nama_pelanggan);
            this.stat.setInt(3,t.id_menu);
            this.stat.setString(4,t.tanggal);
            this.stat.setString(5,t.waktu);
            this.stat.setInt(6, t.no_meja);
            this.stat.setInt(7, t.jumlah_orang);
            this.stat.setString(8,t.nama_menu);
            this.stat.setInt(9, t.harga);
            this.stat.setInt(10, t.jumlah_beli);
            this.stat.setInt(11, t.total_bayar);
            int pilihan = JOptionPane.showConfirmDialog(null,"Tanggal: "+t.tanggal+
                    "\n Nama Pelanggan: "+t.nama_pelanggan+
                    "\n Pembelian: "+t.nama_menu+
                    "\nTotal Bayar: "+t.total_bayar+"\n",
                    "Tambahkan Transaksi?",
                    JOptionPane.YES_NO_OPTION);
            if(pilihan == JOptionPane.YES_NO_OPTION){
                this.stat.executeUpdate();
                refreshTabel();
            }else{
                refreshTabel();
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_inputActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
            transaksi t = new transaksi();
            t.id_transaksi = Integer.parseInt(txt_idtransaksi.getText());
            this.stat = d.getCon().prepareStatement("update transaksi set nama_pelanggan=?,id_menu=?,tanggal=?,"
                    + "waktu=?,no_meja=?,jumlah_orang=?,nama_menu=?,harga=?,jumlah_beli=?,total_bayar=? where id_transaksi=?");
            this.stat.setString(1, t.nama_pelanggan);
             this.stat.setInt(2, t.id_menu);
            this.stat.setString(3, t.tanggal);
            this.stat.setString(4, t.waktu);
            this.stat.setInt(5, t.no_meja);
            this.stat.setInt(6, t.jumlah_orang);
            this.stat.setString(7, t.nama_menu);
            this.stat.setInt(8,t.harga);
            this.stat.setInt(9, t.jumlah_beli);
            this.stat.setInt(10, t.total_bayar);
            this.stat.setInt(11, t.id_transaksi);
            this.stat.executeUpdate();
            refreshTabel();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_layoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_layoutActionPerformed
        LayoutMeja lay = new LayoutMeja();
        lay.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_layoutActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        Menu_Makanan menu = new Menu_Makanan();
        menu.setVisible(true);
        this.setVisible(false);
        menu.btn_input.setEnabled(false);
        menu.btn_update.setEnabled(false);
        menu.btn_delete.setEnabled(false);
        menu.btn_transaksi.setEnabled(true);
        
        
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_invoiceActionPerformed
        invoice invoice = new invoice();
        invoice.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_invoiceActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_logoutActionPerformed

    private void table_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_transaksiMouseClicked
        txt_waktu.setText(model.getValueAt(table_transaksi.getSelectedRow(),4).toString());
        txt_jumlahorang.setText(model.getValueAt(table_transaksi.getSelectedRow(),6).toString());
        txt_idtransaksi.setText(model.getValueAt(table_transaksi.getSelectedRow(),0).toString());
        txt_namapelanggan.setText(model.getValueAt(table_transaksi.getSelectedRow(),1).toString());
        txt_jumlahbeli.setText(model.getValueAt(table_transaksi.getSelectedRow(),9).toString());
        txt_totalbayar.setText(model.getValueAt(table_transaksi.getSelectedRow(),10).toString());
    }//GEN-LAST:event_table_transaksiMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try {
            transaksi t = new transaksi();
            t.id_transaksi = Integer.parseInt(txt_idtransaksi.getText());
            this.stat = d.getCon().prepareStatement("delete from transaksi where id_transaksi=?");
            this.stat.setInt(1,t.id_transaksi);
            this.stat.executeUpdate();
            refreshTabel();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailReservasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_input;
    private javax.swing.JButton btn_invoice;
    private javax.swing.JButton btn_layout;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> comb_idmenu;
    private javax.swing.JComboBox<String> comb_nomeja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_transaksi;
    private javax.swing.JTextField txt_idtransaksi;
    private javax.swing.JTextField txt_jumlahbeli;
    private javax.swing.JTextField txt_jumlahorang;
    private javax.swing.JTextField txt_namapelanggan;
    private com.toedter.calendar.JDateChooser txt_tanggal;
    private javax.swing.JTextField txt_totalbayar;
    private javax.swing.JTextField txt_waktu;
    // End of variables declaration//GEN-END:variables
}
